on:
  push:
    branches: [main]
  pull_request:
jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix build '.#sd-image'
      - uses: actions/upload-artifact@v3
        with:
          name: sd-image
          path: result
